# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './sr_occluder.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SROccluder(object):
    def setupUi(self, SROccluder):
        SROccluder.setObjectName("SROccluder")
        SROccluder.resize(683, 723)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SROccluder)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(SROccluder)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.selectButton = QtWidgets.QToolButton(self.widget)
        self.selectButton.setIconSize(QtCore.QSize(25, 25))
        self.selectButton.setCheckable(True)
        self.selectButton.setChecked(True)
        self.selectButton.setObjectName("selectButton")
        self.verticalLayout.addWidget(self.selectButton)
        self.moveButton = QtWidgets.QToolButton(self.widget)
        self.moveButton.setIconSize(QtCore.QSize(25, 25))
        self.moveButton.setCheckable(True)
        self.moveButton.setObjectName("moveButton")
        self.verticalLayout.addWidget(self.moveButton)
        self.zoomButton = QtWidgets.QToolButton(self.widget)
        self.zoomButton.setIconSize(QtCore.QSize(25, 25))
        self.zoomButton.setCheckable(True)
        self.zoomButton.setObjectName("zoomButton")
        self.verticalLayout.addWidget(self.zoomButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.rectButton = QtWidgets.QToolButton(self.widget)
        self.rectButton.setIconSize(QtCore.QSize(25, 25))
        self.rectButton.setCheckable(True)
        self.rectButton.setAutoRaise(True)
        self.rectButton.setObjectName("rectButton")
        self.verticalLayout.addWidget(self.rectButton)
        self.ellipseButton = QtWidgets.QToolButton(self.widget)
        self.ellipseButton.setIconSize(QtCore.QSize(25, 25))
        self.ellipseButton.setCheckable(True)
        self.ellipseButton.setAutoRaise(True)
        self.ellipseButton.setObjectName("ellipseButton")
        self.verticalLayout.addWidget(self.ellipseButton)
        self.polygonButton = QtWidgets.QToolButton(self.widget)
        self.polygonButton.setIconSize(QtCore.QSize(25, 25))
        self.polygonButton.setCheckable(True)
        self.polygonButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.polygonButton.setAutoRaise(True)
        self.polygonButton.setObjectName("polygonButton")
        self.verticalLayout.addWidget(self.polygonButton)
        self.lineButton = QtWidgets.QToolButton(self.widget)
        self.lineButton.setIconSize(QtCore.QSize(25, 25))
        self.lineButton.setCheckable(True)
        self.lineButton.setAutoRaise(True)
        self.lineButton.setObjectName("lineButton")
        self.verticalLayout.addWidget(self.lineButton)
        self.arrowButton = QtWidgets.QToolButton(self.widget)
        self.arrowButton.setIconSize(QtCore.QSize(25, 25))
        self.arrowButton.setCheckable(True)
        self.arrowButton.setAutoRaise(True)
        self.arrowButton.setObjectName("arrowButton")
        self.verticalLayout.addWidget(self.arrowButton)
        self.darrowButton = QtWidgets.QToolButton(self.widget)
        self.darrowButton.setIconSize(QtCore.QSize(25, 25))
        self.darrowButton.setCheckable(True)
        self.darrowButton.setAutoRaise(True)
        self.darrowButton.setObjectName("darrowButton")
        self.verticalLayout.addWidget(self.darrowButton)
        self.textButton = QtWidgets.QToolButton(self.widget)
        self.textButton.setIconSize(QtCore.QSize(25, 25))
        self.textButton.setCheckable(True)
        self.textButton.setAutoRaise(True)
        self.textButton.setObjectName("textButton")
        self.verticalLayout.addWidget(self.textButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout.addWidget(self.widget)
        self.graphicsView = SROcclusionView(self.widget_2)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(SROccluder)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_3)

        self.retranslateUi(SROccluder)
        QtCore.QMetaObject.connectSlotsByName(SROccluder)

    def retranslateUi(self, SROccluder):
        _translate = QtCore.QCoreApplication.translate
        SROccluder.setWindowTitle(_translate("SROccluder", "Form"))
        self.selectButton.setText(_translate("SROccluder", "SELECT"))
        self.moveButton.setText(_translate("SROccluder", "MOVE"))
        self.zoomButton.setText(_translate("SROccluder", "ZOOM"))
        self.rectButton.setText(_translate("SROccluder", "RECT"))
        self.ellipseButton.setText(_translate("SROccluder", "ELLIPSE"))
        self.polygonButton.setText(_translate("SROccluder", "POLYGON"))
        self.lineButton.setText(_translate("SROccluder", "LINE"))
        self.arrowButton.setText(_translate("SROccluder", "ARROW"))
        self.darrowButton.setText(_translate("SROccluder", "DARROW"))
        self.textButton.setText(_translate("SROccluder", "TEXT"))
        self.label.setText(_translate("SROccluder", "TextLabel"))
from .custom.sr_occlusion_view import SROcclusionView
