# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './sr_config.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SRConfig(object):
    def setupUi(self, SRConfig):
        SRConfig.setObjectName("SRConfig")
        SRConfig.resize(836, 439)
        self.tabWidgetMain = QtWidgets.QTabWidget(SRConfig)
        self.tabWidgetMain.setGeometry(QtCore.QRect(10, 10, 815, 421))
        self.tabWidgetMain.setDocumentMode(False)
        self.tabWidgetMain.setTabsClosable(False)
        self.tabWidgetMain.setObjectName("tabWidgetMain")
        self.tabSettings = QtWidgets.QWidget()
        self.tabSettings.setObjectName("tabSettings")
        self.cardTypeSelector = QtWidgets.QComboBox(self.tabSettings)
        self.cardTypeSelector.setGeometry(QtCore.QRect(0, -10, 281, 41))
        self.cardTypeSelector.setMaxVisibleItems(10)
        self.cardTypeSelector.setObjectName("cardTypeSelector")
        self.cardTypeSelector.addItem("")
        self.enableCheckBox = QtWidgets.QCheckBox(self.tabSettings)
        self.enableCheckBox.setGeometry(QtCore.QRect(290, -10, 191, 41))
        self.enableCheckBox.setChecked(True)
        self.enableCheckBox.setAutoRepeat(False)
        self.enableCheckBox.setTristate(False)
        self.enableCheckBox.setObjectName("enableCheckBox")
        self.lineTop = QtWidgets.QFrame(self.tabSettings)
        self.lineTop.setGeometry(QtCore.QRect(-70, 30, 1001, 21))
        self.lineTop.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineTop.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineTop.setObjectName("lineTop")
        self.insertAnkiPersistenceCheckBox = QtWidgets.QCheckBox(self.tabSettings)
        self.insertAnkiPersistenceCheckBox.setGeometry(QtCore.QRect(490, -10, 161, 41))
        self.insertAnkiPersistenceCheckBox.setChecked(True)
        self.insertAnkiPersistenceCheckBox.setAutoRepeat(False)
        self.insertAnkiPersistenceCheckBox.setTristate(False)
        self.insertAnkiPersistenceCheckBox.setObjectName("insertAnkiPersistenceCheckBox")
        self.pasteIntoTemplateCheckBox = QtWidgets.QCheckBox(self.tabSettings)
        self.pasteIntoTemplateCheckBox.setGeometry(QtCore.QRect(660, -10, 141, 41))
        self.pasteIntoTemplateCheckBox.setChecked(True)
        self.pasteIntoTemplateCheckBox.setAutoRepeat(False)
        self.pasteIntoTemplateCheckBox.setTristate(False)
        self.pasteIntoTemplateCheckBox.setObjectName("pasteIntoTemplateCheckBox")
        self.partTabs = QtWidgets.QTabWidget(self.tabSettings)
        self.partTabs.setGeometry(QtCore.QRect(0, 50, 811, 341))
        self.partTabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.partTabs.setElideMode(QtCore.Qt.ElideLeft)
        self.partTabs.setTabsClosable(False)
        self.partTabs.setMovable(False)
        self.partTabs.setObjectName("partTabs")
        self.iterationTab = QtWidgets.QWidget()
        self.iterationTab.setObjectName("iterationTab")
        self.iterationTabs = QtWidgets.QTabWidget(self.iterationTab)
        self.iterationTabs.setGeometry(QtCore.QRect(0, 0, 811, 281))
        self.iterationTabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.iterationTabs.setElideMode(QtCore.Qt.ElideLeft)
        self.iterationTabs.setTabsClosable(True)
        self.iterationTabs.setMovable(True)
        self.iterationTabs.setObjectName("iterationTabs")
        self.iterationTab1 = QtWidgets.QWidget()
        self.iterationTab1.setObjectName("iterationTab1")
        self.iterationTabs.addTab(self.iterationTab1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.iterationTabs.addTab(self.tab_2, "")
        self.iterationButtons = QtWidgets.QFrame(self.iterationTab)
        self.iterationButtons.setGeometry(QtCore.QRect(110, 280, 691, 31))
        self.iterationButtons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.iterationButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.iterationButtons.setObjectName("iterationButtons")
        self.duplicateIterationPushButton = QtWidgets.QPushButton(self.iterationButtons)
        self.duplicateIterationPushButton.setGeometry(QtCore.QRect(490, 0, 201, 32))
        self.duplicateIterationPushButton.setCheckable(False)
        self.duplicateIterationPushButton.setChecked(False)
        self.duplicateIterationPushButton.setObjectName("duplicateIterationPushButton")
        self.copyFrontsideToBacksidePushButton = QtWidgets.QPushButton(self.iterationButtons)
        self.copyFrontsideToBacksidePushButton.setGeometry(QtCore.QRect(290, 0, 201, 32))
        self.copyFrontsideToBacksidePushButton.setCheckable(False)
        self.copyFrontsideToBacksidePushButton.setChecked(False)
        self.copyFrontsideToBacksidePushButton.setObjectName("copyFrontsideToBacksidePushButton")
        self.copyBacksideToFrontsidePushButton = QtWidgets.QPushButton(self.iterationButtons)
        self.copyBacksideToFrontsidePushButton.setGeometry(QtCore.QRect(90, 0, 201, 32))
        self.copyBacksideToFrontsidePushButton.setCheckable(False)
        self.copyBacksideToFrontsidePushButton.setChecked(False)
        self.copyBacksideToFrontsidePushButton.setObjectName("copyBacksideToFrontsidePushButton")
        self.partTabs.addTab(self.iterationTab, "")
        self.injectionTab = QtWidgets.QWidget()
        self.injectionTab.setObjectName("injectionTab")
        self.injectionTabs = QtWidgets.QTabWidget(self.injectionTab)
        self.injectionTabs.setGeometry(QtCore.QRect(0, 0, 821, 281))
        self.injectionTabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.injectionTabs.setElideMode(QtCore.Qt.ElideLeft)
        self.injectionTabs.setTabsClosable(True)
        self.injectionTabs.setMovable(True)
        self.injectionTabs.setObjectName("injectionTabs")
        self.iterationTab1_3 = QtWidgets.QWidget()
        self.iterationTab1_3.setObjectName("iterationTab1_3")
        self.injectionTabs.addTab(self.iterationTab1_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.injectionTabs.addTab(self.tab, "")
        self.injectionButtons = QtWidgets.QFrame(self.injectionTab)
        self.injectionButtons.setGeometry(QtCore.QRect(120, 280, 681, 31))
        self.injectionButtons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.injectionButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.injectionButtons.setObjectName("injectionButtons")
        self.createNewInjectionPushButton = QtWidgets.QPushButton(self.injectionButtons)
        self.createNewInjectionPushButton.setGeometry(QtCore.QRect(480, 0, 201, 32))
        self.createNewInjectionPushButton.setCheckable(False)
        self.createNewInjectionPushButton.setChecked(False)
        self.createNewInjectionPushButton.setObjectName("createNewInjectionPushButton")
        self.createNewStatementPushButton = QtWidgets.QPushButton(self.injectionButtons)
        self.createNewStatementPushButton.setGeometry(QtCore.QRect(280, 0, 201, 32))
        self.createNewStatementPushButton.setCheckable(False)
        self.createNewStatementPushButton.setChecked(False)
        self.createNewStatementPushButton.setObjectName("createNewStatementPushButton")
        self.deleteCurrentStatementPushButton = QtWidgets.QPushButton(self.injectionButtons)
        self.deleteCurrentStatementPushButton.setGeometry(QtCore.QRect(80, 0, 201, 32))
        self.deleteCurrentStatementPushButton.setCheckable(False)
        self.deleteCurrentStatementPushButton.setChecked(False)
        self.deleteCurrentStatementPushButton.setObjectName("deleteCurrentStatementPushButton")
        self.validateConditionsPushButton = QtWidgets.QPushButton(self.injectionTab)
        self.validateConditionsPushButton.setGeometry(QtCore.QRect(0, 280, 201, 32))
        self.validateConditionsPushButton.setCheckable(False)
        self.validateConditionsPushButton.setChecked(False)
        self.validateConditionsPushButton.setObjectName("validateConditionsPushButton")
        self.injectionButtons.raise_()
        self.validateConditionsPushButton.raise_()
        self.injectionTabs.raise_()
        self.partTabs.addTab(self.injectionTab, "")
        self.tabWidgetMain.addTab(self.tabSettings, "")
        self.tabAbout = QtWidgets.QWidget()
        self.tabAbout.setObjectName("tabAbout")
        self.aboutText = QtWidgets.QTextBrowser(self.tabAbout)
        self.aboutText.setGeometry(QtCore.QRect(10, 10, 811, 391))
        self.aboutText.setOpenExternalLinks(True)
        self.aboutText.setObjectName("aboutText")
        self.tabWidgetMain.addTab(self.tabAbout, "")
        self.buttonBox = QtWidgets.QDialogButtonBox(SRConfig)
        self.buttonBox.setGeometry(QtCore.QRect(650, 430, 181, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(SRConfig)
        self.tabWidgetMain.setCurrentIndex(0)
        self.partTabs.setCurrentIndex(0)
        self.iterationTabs.setCurrentIndex(1)
        self.injectionTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SRConfig)

    def retranslateUi(self, SRConfig):
        _translate = QtCore.QCoreApplication.translate
        SRConfig.setWindowTitle(_translate("SRConfig", "Set Randomizer Settings"))
        self.tabSettings.setWhatsThis(_translate("SRConfig", "<html><head/><body><p><br/></p></body></html>"))
        self.cardTypeSelector.setToolTip(_translate("SRConfig", "<html><head/><body><p>Select the CardType for which you want to change the SR settings.</p></body></html>"))
        self.cardTypeSelector.setItemText(0, _translate("SRConfig", "CardType"))
        self.enableCheckBox.setToolTip(_translate("SRConfig", "<html><head/><body><p>Check this if you want to SR for this card type. Uncheck this option for all card types, before you decide to uninstall SR.</p></body></html>"))
        self.enableCheckBox.setText(_translate("SRConfig", "Enable Set Randomizer (SR)"))
        self.insertAnkiPersistenceCheckBox.setToolTip(_translate("SRConfig", "<html><head/><body><p>Advanced. Inject anki-persistence. You should only uncheck this, if you already use anki-persistence in your templates, and you don\'t want to include it twice. </p></body></html>"))
        self.insertAnkiPersistenceCheckBox.setText(_translate("SRConfig", "Insert anki-persistence"))
        self.pasteIntoTemplateCheckBox.setToolTip(_translate("SRConfig", "<html><head/><body><p>Check this if you want to paste the SR code directly into the template. This is recommended.</p><p>If you uncheck this, SR will create a file in your media folder containing the code. However this option is slower, and you might notice lag. If you can live with this lag, uncheck.</p></body></html>"))
        self.pasteIntoTemplateCheckBox.setText(_translate("SRConfig", "Paste into template"))
        self.iterationTabs.setTabText(self.iterationTabs.indexOf(self.iterationTab1), _translate("SRConfig", "Iteration XXX"))
        self.iterationTabs.setTabText(self.iterationTabs.indexOf(self.tab_2), _translate("SRConfig", "Iteration 2"))
        self.duplicateIterationPushButton.setText(_translate("SRConfig", "Duplicate Current Iteration"))
        self.copyFrontsideToBacksidePushButton.setText(_translate("SRConfig", "Copy Frontside to Backside"))
        self.copyBacksideToFrontsidePushButton.setText(_translate("SRConfig", "Copy Backside to Frontside"))
        self.partTabs.setTabText(self.partTabs.indexOf(self.iterationTab), _translate("SRConfig", "Iterations"))
        self.injectionTabs.setTabText(self.injectionTabs.indexOf(self.iterationTab1_3), _translate("SRConfig", "Injection XXX"))
        self.injectionTabs.setTabText(self.injectionTabs.indexOf(self.tab), _translate("SRConfig", "I2"))
        self.createNewInjectionPushButton.setText(_translate("SRConfig", "Create New Injection"))
        self.createNewStatementPushButton.setText(_translate("SRConfig", "Create New Statement"))
        self.deleteCurrentStatementPushButton.setText(_translate("SRConfig", "Delete Current Statement"))
        self.validateConditionsPushButton.setText(_translate("SRConfig", "Validate Conditions"))
        self.partTabs.setTabText(self.partTabs.indexOf(self.injectionTab), _translate("SRConfig", "Injections"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabSettings), _translate("SRConfig", "Settings"))
        self.aboutText.setHtml(_translate("SRConfig", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-weight:600;\">Anki Set Randomizer</span><span style=\" font-family:\'.SF NS Text\';\"> was developed by </span><a href=\"https://github.com/hgiesel\"><span style=\" font-family:\'.SF NS Text\'; text-decoration: underline; color:#0000ff;\">Henrik Giesel (hgiesel)</span></a><span style=\" font-family:\'.SF NS Text\';\">. <br />🐇 If you like my work consider supporting me on </span><a href=\"https://ko-fi.com/hgiesel\"><span style=\" font-family:\'.SF NS Text\'; text-decoration: underline; color:#0000ff;\">Ko-Fi</span></a><span style=\" font-family:\'.SF NS Text\';\">. 🐇</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-weight:600;\">Anki Persistence</span><span style=\" font-family:\'.SF NS Text\';\"> was developed by </span><a href=\"https://github.com/SimonLammer/anki-persistence\"><span style=\" font-family:\'.SF NS Text\'; text-decoration: underline; color:#0000ff;\">Simmon Lammer</span></a><span style=\" font-family:\'.SF NS Text\';\">.<br /></span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\';\">For more information about how to use Set Randomizer, you should check out </span><a href=\"https://hgiesel.github.io/anki-set-randomizer/\"><span style=\" font-family:\'.SF NS Text\'; text-decoration: underline; color:#0000ff;\">the docs</span></a><span style=\" font-family:\'.SF NS Text\';\"> (work in progress).</span></p></body></html>"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabAbout), _translate("SRConfig", "About"))
