#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Anki Add-on: Anki Set Randomizer

Please do not edit this file unless you know what you are doing.

Copyright: (c) 2019 Henrik Giesel <https://github.com/hgiesel>
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl.html>
"""

from .src import main
