"""
Anki Add-on: Anki Set Randomizer

Please do not edit this file unless you know what you are doing.

Copyright: (c) 2019 Henrik Giesel <https://github.com/hgiesel>
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl.html>
"""

from aqt import mw
import os.path as path
if mw.addonManager.addonName(path.dirname(__file__)) != 'Set Randomizer':
    dir_path = path.dirname(path.realpath(__file__))

    with open(path.join(dir_path, 'manifest.json')) as f:
        with open(path.join(dir_path, 'meta.json')) as f_old:
            import json
            mw.addonManager.writeAddonMeta(dir_path, json.load(f).update({
                'config': json.load(f_old)['config']
            }))

from .src import main
