= Anki Set Randomizer

*Set Randomizer* (SR) is a Template Engine for learning cards.
It supports all platforms that link:https://github.com/SimonLammer/anki-persistence[Anki Persistence] supports.
This includes *AnkiMobile*, *AnkiDroid*, and *AnkiWeb*.
It also supports all note types, including Cloze and even Glutanimate's link:https://ankiweb.net/shared/info/969733775[Cloze Overlapper].

.Installing Set Randomizer:
Just installing the add-on won't affect your note types at all.
You have to manually enable Set Randomizer to use its functionality.
Under "Tools" in the menu bar, you will find a new option "Set Randomizer Settings...".
Here you can define which note types should employ SR, and where the content is locate via a CSS query.
Employing SR will paste the templating engine into the selected note type's card template in the form of a big script tag.
You can confirm this by checking out the note type under "Tools &gt; Manage Note Types", selecting your note type, and pressing "Cards...".
You will be able to find the Set Randomizer JavaScript in each card type, in both the front and the back template.

.Removing Set Randomizer:
To remove the SR from one note type, go to "Tools &gt; Set Randomizer Settings...", and uncheck "Enable Set Randomizer".
Confirming the dialogue will remove the script tag from the templates.
If you wish to remove the add-on completely, make sure you first disable it for all of your note types individually.

.Using Set Randomizer:
In note types for which you enabled Set Randomizer, you can now use a special syntax to help you design your learning cards.
This syntax looks like this: `[[apple::banana::cherry]]`.
This would create a randomized list of the items "apple", "banana", and "cherry".
However this is only the tip of the iceberg.
SR has a ton of features, so many in fact, that I created an link:https://raw.githubusercontent.com/hgiesel/anki-set-randomizer/master/Set_Randomizer_Demo_Deck.apkg[Anki deck], which serves as an introduction and tutorial to SR.
This deck works without installing the add-on, so if you want to have a glance at the features, before installing the add-on, you can do that, too.

If you have any issues, or question, consider link:https://github.com/hgiesel/anki-set-randomizer[writing an issue on GitHub], link:https://www.reddit.com/user/hgiesel[contacting me on Reddit], or link:mailto:hengiesel@gmail.com[writing me a plain old email].

== Related Add-ons

==== link:https://ankiweb.net/shared/info/1280092568[Insert Randomized Lists]
* allows for randomization of a list of items in a single field, expressed in an unordered list
* does not work on Mobile

==== link:https://ankiweb.net/shared/info/1491702369[Sequence Inserter]
* can generate random integers and choose random elements from predefined sets
* does not work on Mobile, or 2.1

==== link:https://ankiweb.net/shared/info/1484572887[Field Modifier: Random Item]
* picks a random item from a Field
* does not work on Mobile, or 2.1

==== link:https://ankiweb.net/shared/info/413154037[Multiple Choice]
* uses multiple fields, to contain several items, coloring the right choice in green
* does not work on Mobile
