= Generators
:stylesheet: ../style.css
:toc: macro
:sectnums:
:sectanchors:
:idprefix:

<< link:../index.html[BACK TO TABLE OF CONTENTS]

toc::[]

== Value Sets

Generators sets allow you to define text elements without automatically displaying them.

If you define inline elements, like e.g.  `[[alligator::bear::cat]`, you often have to copy, move, or delete in order to achieve what you want.
If you utilize generators sets, you have more control over where you want them the text elements to appear in the first place.

== Defining Value Sets

Value sets start with a *dollar sign*, which is followed by the value set name.
After this follows the *delimiter*, which is used to delimit all the values of the value set.
Then follows the list of *values*, delimited by the delimiter.

++++
include::examples/generators/example-10.html[]
++++

The first value set is named `v1`, and uses the `|` character as its delimiter.
The second value set is named `vs2`, and uses the `,` character as its delimiter.
Both sets have the values "alligator", "bear", and "cat".

There are two ways to interact with value sets:

. <<picking_from_value_sets,Picking>>
. <<evaluating_value_sets,Evaluating>>

== Picking From Value Sets

Picking from a value set will generate an element anywhere in the document.

----
$pick([count, ]value_set[, uniqueness_constraint])
----

Defining a `count` will pick _count_ elements.
For more on `uniqueness_constraint`, refer to <<uniqueness_constraints,Uniqueness
Constraints>>.

++++
include::examples/generators/example-20.html[]
++++

== Evaluating Value Sets

Evaluating a value set will generate an element in the place of the original value set.

----
$eval([count, ]value_set[, uniqueness_constraint])
----

Defining a `count` will pick _count_ elements.
For more on `uniqueness_constraint`, refer to <<Uniqueness_Constraints,Uniqueness
Constraints>>.

++++
include::examples/generators/example-30.html[]
++++

== Generating Numerical Values


== Uniqueness Constraints

If you don't want to generate a single element multiple times when picking at random, you can also define uniqueness constraints.
Uniqueness constraints record elements you've generated and will trigger a second generation, if you happen to generate an element twice.

++++
include::examples/generators/example-50.html[]
++++

<< link:../index.html[BACK TO TABLE OF CONTENTS]
