= Generators
:stylesheet: ../style.css
:toc:
:sectnums:

[[Value_Sets]]
== Value Sets

Generators sets allow you to define text elements without automatically displaying them.

If you define inline elements, like e.g.  `[[alligator::bear:cat]`, you often have to copy, move, or delete in order to achieve what you want.
If you utilize generators sets, you have more control over where you want them the text elements to appear in the first place.

[[Defining_Value_Sets]]
== Defining Value Sets

Value sets start with a dollar sign, which is followed by the value set name.
After this follows a delimiter, which will be used to delimit all following values.
Then follows the list of values.

++++
include::examples/generators/example-10.html[]
++++

The first value set is named `v1`, and uses the `|` character as its delimiter.
The second value set is named `vs2`, and uses the `,` character as its delimiter.

[[Picking_From_Value_Sets]]
== Picking From Value Sets

Syntax for picking:

----
$pick(value_set[, uniqueness_constraint])
----

++++
include::examples/generators/example-20.html[]
++++

[[Evaluating_Value_Sets]]
== Evaluating Value Sets

----
$eval(value_set[, uniqueness_constraint])
----

[[Generating_Numerical_Values]]
== Generating Numerical Values


[[Uniqueness_Constraints]]
== Uniqueness Constraints

If you don't want to generate a single element multiple times when picking at
random, you can also define uniqueness constraints. Uniqueness constraints
record elements you've generated and will trigger a second generation, if you
happen to generate an element twice.
