# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './sr_iteration_tab.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SRIterationTab(object):
    def setupUi(self, SRIterationTab):
        SRIterationTab.setObjectName("SRIterationTab")
        SRIterationTab.resize(776, 425)
        self.gridLayout = QtWidgets.QGridLayout(SRIterationTab)
        self.gridLayout.setObjectName("gridLayout")
        self.upPushButton = QtWidgets.QPushButton(SRIterationTab)
        self.upPushButton.setObjectName("upPushButton")
        self.gridLayout.addWidget(self.upPushButton, 3, 5, 1, 1)
        self.duplicatePushButton = QtWidgets.QPushButton(SRIterationTab)
        self.duplicatePushButton.setObjectName("duplicatePushButton")
        self.gridLayout.addWidget(self.duplicatePushButton, 3, 1, 1, 1)
        self.deletePushButton = QtWidgets.QPushButton(SRIterationTab)
        self.deletePushButton.setObjectName("deletePushButton")
        self.gridLayout.addWidget(self.deletePushButton, 3, 2, 1, 1)
        self.importButton = QtWidgets.QPushButton(SRIterationTab)
        self.importButton.setObjectName("importButton")
        self.gridLayout.addWidget(self.importButton, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 3, 1, 1)
        self.downPushButton = QtWidgets.QPushButton(SRIterationTab)
        self.downPushButton.setObjectName("downPushButton")
        self.gridLayout.addWidget(self.downPushButton, 3, 4, 1, 1)
        self.iterationsTable = QtWidgets.QTableWidget(SRIterationTab)
        self.iterationsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.iterationsTable.setProperty("showDropIndicator", False)
        self.iterationsTable.setDragEnabled(False)
        self.iterationsTable.setDragDropOverwriteMode(False)
        self.iterationsTable.setAlternatingRowColors(True)
        self.iterationsTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.iterationsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.iterationsTable.setShowGrid(True)
        self.iterationsTable.setGridStyle(QtCore.Qt.SolidLine)
        self.iterationsTable.setCornerButtonEnabled(False)
        self.iterationsTable.setObjectName("iterationsTable")
        self.iterationsTable.setColumnCount(5)
        self.iterationsTable.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.iterationsTable.setItem(2, 4, item)
        self.iterationsTable.horizontalHeader().setCascadingSectionResizes(False)
        self.iterationsTable.horizontalHeader().setDefaultSectionSize(200)
        self.iterationsTable.horizontalHeader().setStretchLastSection(True)
        self.iterationsTable.verticalHeader().setVisible(True)
        self.iterationsTable.verticalHeader().setCascadingSectionResizes(True)
        self.iterationsTable.verticalHeader().setHighlightSections(True)
        self.iterationsTable.verticalHeader().setMinimumSectionSize(35)
        self.iterationsTable.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout.addWidget(self.iterationsTable, 0, 0, 1, 6)

        self.retranslateUi(SRIterationTab)
        self.iterationsTable.cellActivated['int','int'].connect(self.deletePushButton.toggle)
        QtCore.QMetaObject.connectSlotsByName(SRIterationTab)

    def retranslateUi(self, SRIterationTab):
        _translate = QtCore.QCoreApplication.translate
        SRIterationTab.setWindowTitle(_translate("SRIterationTab", "Form"))
        self.upPushButton.setText(_translate("SRIterationTab", "▲ Up"))
        self.duplicatePushButton.setText(_translate("SRIterationTab", "⊕ Duplicate"))
        self.deletePushButton.setText(_translate("SRIterationTab", "⌫ Delete"))
        self.importButton.setText(_translate("SRIterationTab", "⎈ Import / Export"))
        self.downPushButton.setText(_translate("SRIterationTab", "▼ Down"))
        self.iterationsTable.setSortingEnabled(False)
        item = self.iterationsTable.verticalHeaderItem(0)
        item.setText(_translate("SRIterationTab", "Iteration 1"))
        item = self.iterationsTable.verticalHeaderItem(1)
        item.setText(_translate("SRIterationTab", "Iteration 2"))
        item = self.iterationsTable.verticalHeaderItem(2)
        item.setText(_translate("SRIterationTab", "Iteration 3"))
        item = self.iterationsTable.horizontalHeaderItem(0)
        item.setText(_translate("SRIterationTab", "Name"))
        item = self.iterationsTable.horizontalHeaderItem(1)
        item.setText(_translate("SRIterationTab", "Front Enabled"))
        item = self.iterationsTable.horizontalHeaderItem(2)
        item.setText(_translate("SRIterationTab", "Front Set Example"))
        item = self.iterationsTable.horizontalHeaderItem(3)
        item.setText(_translate("SRIterationTab", "Back Enabled"))
        item = self.iterationsTable.horizontalHeaderItem(4)
        item.setText(_translate("SRIterationTab", "Back Set Example"))
        __sortingEnabled = self.iterationsTable.isSortingEnabled()
        self.iterationsTable.setSortingEnabled(False)
        item = self.iterationsTable.item(0, 0)
        item.setText(_translate("SRIterationTab", "main"))
        item = self.iterationsTable.item(0, 1)
        item.setText(_translate("SRIterationTab", "✓"))
        item = self.iterationsTable.item(0, 2)
        item.setText(_translate("SRIterationTab", "[[ item1 :: item2 ]]"))
        item = self.iterationsTable.item(0, 3)
        item.setText(_translate("SRIterationTab", "✓"))
        item = self.iterationsTable.item(0, 4)
        item.setText(_translate("SRIterationTab", "[[ item1 :: item2 ]]"))
        item = self.iterationsTable.item(1, 0)
        item.setText(_translate("SRIterationTab", "side"))
        item = self.iterationsTable.item(1, 1)
        item.setText(_translate("SRIterationTab", "✓"))
        item = self.iterationsTable.item(1, 2)
        item.setText(_translate("SRIterationTab", "[b?[ item1 ;; item2 ]]"))
        item = self.iterationsTable.item(1, 3)
        item.setText(_translate("SRIterationTab", "✗"))
        item = self.iterationsTable.item(1, 4)
        item.setText(_translate("SRIterationTab", "[b?[ item1 ;; item2 ]]"))
        item = self.iterationsTable.item(2, 0)
        item.setText(_translate("SRIterationTab", "extra"))
        item = self.iterationsTable.item(2, 1)
        item.setText(_translate("SRIterationTab", "✓"))
        item = self.iterationsTable.item(2, 2)
        item.setText(_translate("SRIterationTab", "[f?[ item1 ;; item 2 ]]"))
        item = self.iterationsTable.item(2, 3)
        item.setText(_translate("SRIterationTab", "✗"))
        item = self.iterationsTable.item(2, 4)
        item.setText(_translate("SRIterationTab", "[f?[ item1 ;; item 2 ]]"))
        self.iterationsTable.setSortingEnabled(__sortingEnabled)
