= Generators
:toc: macro

Generators are the meta elements that are first evaluated in SR. Generators
include the following three commands:

. *value sets*
. *picking values*, with `$pick()`
. *evaluating value sets*, with `$eval()`

toc::[]

== Value sets

Generators sets are a way of defining text elements without automatically
displaying them.

If you define inline elements, like e.g.  `[[alligator::bear:cat]`,
you often have to copy, move, or delete in order to achieve what you want.
If you utilize generators sets, you have more control
over where you want them the text elements to appear in the first place.

++++
include::examples/generators-1.html[]
++++

== Picking from value sets

Syntax for picking:

----
$pick(value_set[, uniqueness_constraint])
----

++++
include::examples/generators-2.html[]
++++

== Evaluating value sets

----
$eval(value_set[, uniqueness_constraint])
----

== Generating numerical values


== Uniqueness constraints

If you don't want to generate a single element multiple times when picking at
random, you can also define uniqueness constraints. Uniqueness constraints
record elements you've generated and will trigger a second generation, if you
happen to generate an element twice.
